#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2024 Fewtarius

### Works around an issue where NetworkManager cannot reconnect to WIFI
### after sleep.
systemctl restart iwd >/dev/null 2>&1
