#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2024 Fewtarius

# The Flip wakes when the lid is closed and the device is suspended
# so, go back into the sleep state.

if [ -f '/proc/acpi/button/lid/LID0/state' ]
then
  (
    for count in $(seq 1 1 5)
    do
      LID_STATE=$(awk '{printf $2}' /proc/acpi/button/lid/LID0/state)
      if [ "${LID_STATE}" = "open" ]
      then
        exit 0
      fi
      sleep .2
    done
    echo mem >/sys/power/state
  ) &
fi
