#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2024 SteamFork (https://github.com/SteamFork)

. /etc/profile

for KEY in WWWHOST WWWUSER WWWROOT SIGNKEY
do
  if [ -z "${!KEY}" ]
  then
    echo "Export ${KEY} before using this script."
    exit 1
  fi
done

case ${1} in
  pkgs)
    for REPO in rel beta minimal
    do
      REPODIR="$(pwd)/packages/steamfork/${REPO}"
      if [ -d "${REPODIR}" ]
      then
        cd ${REPODIR}
        repo-add --sign -k ${SIGNKEY} steamfork.db.tar.gz *zst
        cd -
        ssh -ttq ${WWWUSER}@${WWWHOST} "cd ${WWWROOT}; ln -sf ${WWWROOT}/steamfork/${REPO} steamfork-${REPO}"
      fi
    done
    rsync -av --delete --progress --stats packages/steamfork/ ${WWWUSER}@${WWWHOST}:${WWWROOT}/steamfork/
    ssh -ttq ${WWWUSER}@${WWWHOST} "chown -R www-data:www-data ${WWWROOT}/"
  ;;
  os)
      cat <<EOF >/tmp/index.html
<head>
<meta name="description" content="SteamFork Linux distribution image hosting.">
<meta name="keywords" content="SteamFork, SteamOS, HoloISO, Linux, Gaming, Handheld">
<body>
EOF
    ssh -ttq ${WWWUSER}@${WWWHOST} "cd ${WWWROOT}/; rm -rf steamfork-images-new ||:; cp -rf steamfork-images steamfork-images-new"
    for REL in rel
    do
      BUILDDIR="$(pwd)/builds/${REL}/steamfork-images"
      if [ -e "${BUILDDIR}/latest_${REL}.releasemeta" ]
      then
        source ${BUILDDIR}/latest_${REL}.releasemeta
        IMAGEFILE="$(echo ${IMAGEFILE} | sed 's~_~-~g')"
	ssh -ttq ${WWWUSER}@${WWWHOST} "cd ${WWWROOT}/steamfork-images-new; rm -f \$(ls | grep steamfork_${REL}_ | grep -v ${STAGING_OS_TAG}) latest_${REL}*"
        ssh -ttq ${WWWUSER}@${WWWHOST} "cd ${WWWROOT}/steamfork-images-new/steamfork-installer; rm -f \$(ls | grep steamfork-${REL}- | grep -v ${STAGING_OS_TAG}) latest_${REL}*"
        rsync -av --progress --stats builds/${REL}/steamfork-images/* ${WWWUSER}@${WWWHOST}:${WWWROOT}/steamfork-images-new/
        ssh -ttq ${WWWUSER}@${WWWHOST} "cd ${WWWROOT}/steamfork-images-new/steamfork-installer/; sha256sum ${IMAGEFILE}-x86_64.iso | tee -a ${IMAGEFILE}-x86_64.iso.sha256"
        ssh -ttq ${WWWUSER}@${WWWHOST} "cd ${WWWROOT}/steamfork-images-new/steamfork-installer/; ln -sf ${IMAGEFILE}-x86_64.iso steamfork-${REL}-latest-x86_64.iso"
        ssh -ttq ${WWWUSER}@${WWWHOST} "cd ${WWWROOT}/steamfork-images-new/steamfork-installer/; ln -sf ${IMAGEFILE}-x86_64.iso.sha256 steamfork-${REL}-latest-x86_64.iso.sha256"
        cat <<EOF >>/tmp/index.html
<p>
SteamFork v${STAGING_OS_TAG} (${REL}) installation image: <a href="/steamfork-images/steamfork-installer/${IMAGEFILE}-x86_64.iso">${IMAGEFILE}-x86_64.iso</a>
<br>
SteamFork v${STAGING_OS_TAG} (${REL}) checksum: <a href="/steamfork-images/steamfork-installer/${IMAGEFILE}-x86_64.iso.sha256">${IMAGEFILE}-x86_64.iso.sha256</a>
<p>
EOF
      fi
    done
cat <<EOF >>/tmp/index.html
</body>
</head>
EOF
    scp /tmp/index.html ${WWWUSER}@${WWWHOST}:${WWWROOT}/steamfork-images-new/steamfork-installer/
    ssh -ttq ${WWWUSER}@${WWWHOST} "chown -R www-data:www-data ${WWWROOT}/steamfork-images-new"
    ssh -ttq ${WWWUSER}@${WWWHOST} "rm -rf ${WWWROOT}/steamfork-images; mv ${WWWROOT}/steamfork-images-new/ ${WWWROOT}/steamfork-images"
  ;;
  *)
    ./syncrepo pkgs
    ./syncrepo os
  ;;
esac

