#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023 JELOS (https://github.com/JustEnoughLinuxOS)
# Copyright (C) 2024 Fewtarius

systemctl stop fancontrol

DEVICE_PWM_FAN="$(find /sys/devices/platform/oxp-platform -name pwm1)"
DEVICE_FAN_INPUT="$(find /sys/devices/platform/oxp-platform -name fan*_input)"

echo 1 >${DEVICE_PWM_FAN}
echo 0 >${DEVICE_FAN_INPUT}
