#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023-present Fewtarius

HWID="$(/usr/bin/steamfork-device-id)"

function log() {
  SOURCE=${1//\/*\//}
  MESSAGE=${*#${1}}
  MESSAGE=${MESSAGE# }
  logger -t ${SOURCE} "${MESSAGE}"
}

modules() {
  log $0 "Modules: ${1}"
  case ${1} in
    stop)
      if [ -e "/etc/lib/steamfork_hwsupport/devicequirks/"${HWID}"/modules.bad" ]
      then
        for module in $(cat /etc/lib/steamfork_hwsupport/devicequirks/"${HWID}"/modules.bad)
        do
          EXISTS=$(lsmod | grep ${module})
          if [ $? = 0 ]
          then
            echo ${module} >>/tmp/modules.load
            modprobe -r ${module} >/dev/null 2>&1
          fi
        done
      fi
    ;;
    start)
      if [ -e "/tmp/modules.load" ]
      then
        for module in $(cat /tmp/modules.load)
        do
          MODCNT=0
          MODATTEMPTS=10
          while true
          do
            if (( "${MODCNT}" < "${MODATTEMPTS}" ))
            then
              modprobe ${module%% *} >/dev/null 2>&1
              if [ $? = 0 ]
              then
                break
              fi
            else
              break
            fi
            MODCNT=$((${MODCNT} + 1))
            sleep .5
          done
        done
        rm -f /tmp/modules.load
      fi
    ;;
  esac
}

quirks() {
  for QUIRK in /etc/lib/steamfork_hwsupport/devicequirks/DEFAULT/sleep.d/${1}/* \
	       /etc/lib/steamfork_hwsupport/devicequirks/"${HWID}"/sleep.d/${1}/* \
               /etc/lib/steamfork_hwsupport/customdevicequirks/"${HWID}"/sleep.d/${1}/*
  do
    if [ -f "${QUIRK}" ]
    then
      "${QUIRK}" >/dev/null 2>&1
    fi
  done
}

case $1 in
  pre)
    modules stop
    quirks ${1}
  ;;
  post)
    modules start
    quirks ${1}
  ;;
esac
