#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2024 Fewtarius

. /etc/profile

RESTORE_CPU=$(get_setting sleep.cpugovernor)
RESTORE_GPU=$(set_setting sleep.gpulevel)

for CORE in $(find /sys/devices/system/cpu/cpufreq -name policy*)
do
  echo ${RESTORE_CPU} >${CORE}/scaling_governor
done

for CARD in $(find /sys/class/drm/card* -name power_dpm_force_performance_level)
do
  echo ${RESTORE_GPU} >${CARD}
done
