#!/bin/bash

# Generate calibration matrix for bottom touchscreen
# TODO: Find literally any other way to do this

cat <<EOF | sudo tee /etc/X11/xorg.conf.d/99-touchscreen_orientation.conf
Section "InputClass"
	Identifier "Coordinate Transformation Matrix"
	MatchIsTouchscreen "on"
	MatchDevicePath "/dev/input/event*"
	MatchDriver "libinput"
	Option "CalibrationMatrix" "0 -0.5 0.75 0.37209302 0 0.62790698 0 0 1"
EndSection
EOF
