#!/bin/bash

for USER in $(awk 'BEGIN {FS=":"} {print $1}' /etc/passwd)
do
	FILE_PATH="/home/${USER}/.config/kwinrc"
	if [ ! -f "${FILE_PATH}" ]
	then
		cat <<EOF >${FILE_PATH}
[KSplash]
Theme=com.valve.vapor.deck.desktop
EOF
fi

	chown ${USER}:${USER} ${FILE_PATH}
	chmod 0640 ${FILE_PATH}
done
