#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2024 SteamFork (https://github.com/SteamFork)

PANEL_POWERSAVE_DISABLED=$(steamfork-get-setting amdgpu.powersave.disabled)
if [ -z ${PANEL_POWERSAVE_DISABLED} ]
then
  PANEL_POWERSAVE_DISABLED=0
fi

for NODE in /sys/class/drm/card?/*/amdgpu/panel_power_savings
do
  if (( ${PANEL_POWERSAVE_DISABLED} < 1 )) && \
     [ -e "${NODE}" ]
  then
    echo 1 >${NODE}
  fi
done
