#!/bin/sh

for CODEC in snd_ac97_codec snd_hda_intel
do
  echo 1 >/sys/module/${CODEC}/parameters/power_save
done

### SteamOS introduced services to configure audio, however
### user and system services cannot interact so there is no
### good way to order them.  Until we find a better solution:

/usr/share/pipewire/hardware-profiles/pipewire-hwconfig
/usr/share/wireplumber/hardware-profiles/wireplumber-hwconfig
