#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only

build() {
    add_binary findmnt
    add_runscript
}

help() {
    cat <<HELPEOF
This mounts required filesystems by steamfork, where we can't use
normal drop-ins
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
