# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2025 SteamFork (https://github.com/SteamFork)
# This workflow triggers the build_and_sync workflow for the 3.7 branch when packages are added or modified in the repository.

name: Testing - Packages Build and Sync

on:
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '**'
      - '!PKGBUILD/**'
    branches:
      - 3.7
  workflow_dispatch:

jobs:
  trigger_build_and_sync:
    runs-on: 3.7
    if: contains(github.ref, 'refs/heads/3.7')

    steps:
      - name: Set up Git
        run: |
          if [ ! -d ".git" ]; then
            git init
            git remote add origin https://github.com/${{ github.repository }}.git
          fi
          git fetch origin ${{ github.ref_name }}
          if [ $(git branch --list ${{ github.ref_name }}) ]; then
            git checkout ${{ github.ref_name }}
          else
            git checkout -b ${{ github.ref_name }} origin/${{ github.ref_name }}
          fi

      - name: Install GitHub CLI
        run: |
          sudo pacman -Sy --noconfirm github-cli

      - name: Authenticate GitHub CLI
        run: |
          gh auth status || echo "${{ secrets.WORKFLOW_TOKEN }}" | gh auth login --with-token

      - name: Set default repository
        run: |
          gh repo set-default ${{ github.repository }}

      - name: List available workflows
        run: |
          gh workflow list
          
      - name: Trigger build_and_sync workflow
        run: |
          gh workflow run build_and_sync.yml --ref ${{ github.ref }} -f runner_tag=${{ github.ref }}
