name: Build All Packages

on:
  workflow_dispatch:

jobs:
  build_all_packages:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create blank repository
        run: |
          eval $(make -s env)
          mkdir -p "${REPO_DIR}/${STEAMOS_VERSION}/os/${OS_ARCH}"
          repo-add "${REPO_DIR}/${STEAMOS_VERSION}/os/${OS_ARCH}/steamfork.db.tar.gz"

      - name: Set up environment
        run: |
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm make gpgme pikaur openssh

      - name: Cache GPG key
        id: gpg-key
        uses: actions/cache@v2
        with:
          path: ~/.gnupg
          key: ${{ runner.os }}-gpg-key
          restore-keys: |
            ${{ runner.os }}-gpg-key

      - name: Cache SSH key
        id: ssh-key
        uses: actions/cache@v2
        with:
          path: ~/.ssh
          key: ${{ runner.os }}-ssh-key
          restore-keys: |
            ${{ runner.os }}-ssh-key

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set GPG trust level
        run: |
          echo "${{ secrets.GPG_KEY_ID }}:6:" | gpg --batch --yes --import-ownertrust

      - name: Build all packages
        run: |
          ./scripts/build_all_packages.sh

#      - name: Sync packages
#        run: make packages-sync

#      - name: Sync mirrors
#        run: make mirrors-sync
