name: Automated Build and Sync (main)

on:
  push:
    branches:
      - main
    paths:
      - 'PKGBUILD/**'
  workflow_dispatch:

jobs:
  trigger_build_and_sync:
    runs-on: self-hosted
    if: contains(github.ref, 'refs/heads/main')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Install GitHub CLI
        run: |
          sudo pacman -Sy --noconfirm github-cli

      - name: Authenticate GitHub CLI
        run: |
          gh auth status || echo "${{ secrets.WORKFLOW_TOKEN }}" | gh auth login --with-token

      - name: Set default repository
        run: |
          gh repo set-default ${{ github.repository }}

      - name: List available workflows
        run: |
          gh workflow list
          
      - name: Trigger build_and_sync workflow
        run: |
          gh workflow run build_and_sync.yml --ref main