name: Automated Package Build and Sync

on:
  branch:
    - main
  push:
    paths:
      - 'PKGBUILD/**'
  workflow_dispatch:

jobs:
  build_and_sync:
    timeout-minutes: 1440
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Cache GPG key
        id: gpg-key
        uses: actions/cache@v4
        with:
          path: ~/.gnupg
          key: ${{ runner.os }}-gpg-key
          restore-keys: |
            ${{ runner.os }}-gpg-key

      - name: Cache SSH key
        id: ssh-key
        uses: actions/cache@v2
        with:
          path: ~/.ssh
          key: ${{ runner.os }}-ssh-key
          restore-keys: |
            ${{ runner.os }}-ssh-key

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set GPG trust level
        run: |
          echo "${{ secrets.GPG_KEY_ID }}:6:" | gpg --batch --yes --import-ownertrust

      - name: Trust GPG key for pacman
        run: |
          echo "$GPG_PRIVATE_KEY" > /tmp/private.key
          sudo pacman-key --init
          sudo pacman-key --add /tmp/private.key
          sudo pacman-key --lsign-key ${{ secrets.GPG_KEY_ID }}
          rm /tmp/private.key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Run checksum_pkgbuild script
        id: checksum
        run: |
          OUTPUT=$(./scripts/checksum_pkgbuild.sh)
          echo "::set-output name=packages::$OUTPUT"

      - name: Build with dependencies
        run: |
          PACKAGES="${{ steps.checksum.outputs.packages }}"
          IFS=' ' read -r -a PACKAGE_ARRAY <<< "$PACKAGES"
          for PKG in "${PACKAGE_ARRAY[@]}"; do
            ./scripts/build_with_dependencies "$PKG"
          done

#      - name: Sync packages
#        run: make packages-sync

#      - name: Sync mirrors
#        run: make mirrors-sync
