name: Build All Packages

on:
  workflow_dispatch:

jobs:
  build_all_packages:
    timeout-minutes: 1440
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Cache GPG key
        id: gpg-key
        uses: actions/cache@v3
        with:
          path: ~/.gnupg
          key: ${{ runner.os }}-gpg-key
          restore-keys: |
            ${{ runner.os }}-gpg-key

      - name: Cache SSH key
        id: ssh-key
        uses: actions/cache@v3
        with:
          path: ~/.ssh
          key: ${{ runner.os }}-ssh-key
          restore-keys: |
            ${{ runner.os }}-ssh-key

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set GPG trust level
        run: |
          echo "${{ secrets.GPG_KEY_ID }}:5:" | gpg --batch --yes --import-ownertrust

      - name: Trust GPG key for pacman
        run: |
          echo "$GPG_PRIVATE_KEY" > /tmp/private.key
          sudo pacman-key --init
          sudo pacman-key --add /tmp/private.key
          sudo pacman-key --lsign-key ${{ secrets.GPG_KEY_ID }}
          rm /tmp/private.key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Create blank repository
        run: |
          eval $(make -s env)
          mkdir -p "${REPO_DIR}/${STEAMOS_VERSION}/os/${OS_ARCH}" ||:
          repo-add -s -k ${{ secrets.GPG_KEY_ID }} "${REPO_DIR}/${STEAMOS_VERSION}/os/${OS_ARCH}/steamfork.db.tar.gz"

      - name: Build all packages
        run: |
          make packages-all

#      - name: Sync packages
#        run: make packages-sync

#      - name: Sync mirrors
#        run: make mirrors-sync
