name: Build
permissions:
  contents: write
on:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 1440
    runs-on: main
    steps:
      - uses: actions/checkout@v4
        name: checkout
        with:
          clean: false
          ref: "${{ steps.branch.outputs.branch }}"
      - name: Set the tag
        id: tag
        run: echo "tag=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Set the version
        id: version
        run: echo "version=$(date +'%Y%m%d.%H%M')" >> $GITHUB_OUTPUT
      - name: Build Release Images
        run: |
          set -e
          make image-clean
          make build-clean
          make image rel BUILD_VER="${{ steps.version.outputs.version }}"
