# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2024 SteamFork (https://github.com/SteamFork)
# This workflow builds and releases official installation and update images for the SteamFork distribution.

name: Image Build and Release (Stable)
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 1440
    runs-on: 3.6
    steps:
      - uses: actions/checkout@v4
        name: checkout
        with:
          clean: false
          ref: "${{ steps.branch.outputs.branch }}"
      - name: Set the tag
        id: tag
        run: echo "tag=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Set the version
        id: version
        run: echo "version=$(date +'%Y%m%d.%H%M')" >> $GITHUB_OUTPUT
      - name: Build Release Images
        run: |
          set -e
          make image stable BUILD_VER="${{ steps.version.outputs.version }}"
  sync:
    if: github.repository == 'SteamFork/distribution' && startsWith(github.ref, 'refs/tags/2')
    timeout-minutes: 1440
    runs-on: 3.6
    needs: build
    steps:
      - name: Sync release images to the primary instance
        run: |
          set -e
          make images-sync
      - name: Sync images to each mirror
        run: |
          set -e
          make mirrors-sync
  release:
    if: github.repository == 'SteamFork/distribution' && startsWith(github.ref, 'refs/tags/2')
    timeout-minutes: 1440
    runs-on: 3.6
    needs: sync
    steps:
      - name: Release images to the public
        run: |
          set -e
          make images-release
      - name: Create a release snapshot.
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.tag.outputs.tag }}"
          body: |
            ## Downloads
            This release contains a snapshot of the repository tree and a list of packages and their versions in this release.  Downloadable images are available at [SteamFork.org](https://www.steamfork.org/images/installer/) with updates available OTA.  A download link to the latest installation image can be found below.

            | Branch | URL | Checksum |
            | -- | -- | -- |
            | Primary | [LATEST](https://www.steamfork.org/images/installer/steamfork-rel-latest-x86_64.iso) | [SHA256](https://www.steamfork.org/images/installer/steamfork-rel-latest-x86_64.iso.sha256) |
            | New York | [LATEST](https://www1.ny.steamfork.org/images/installer/steamfork-rel-latest-x86_64.iso) | [SHA256](https://www1.ny.steamfork.org/images/installer/steamfork-rel-latest-x86_64.iso.sha256) ||
            | Dallas | [LATEST](https://www1.da.steamfork.org/images/installer/steamfork-rel-latest-x86_64.iso) | [SHA256](https://www1.da.steamfork.org/images/installer/steamfork-rel-latest-x86_64.iso.sha256) ||
            | San Jose | [LATEST](https://www1.sj.steamfork.org/images/installer/steamfork-rel-latest-x86_64.iso) | [SHA256](https://www1.sj.steamfork.org/images/installer/steamfork-rel-latest-x86_64.iso.sha256) ||
            | Ashburn | [LATEST](https://www1.as.steamfork.org/images/installer/steamfork-rel-latest-x86_64.iso) | [SHA256](https://www1.as.steamfork.org/images/installer/steamfork-rel-latest-x86_64.iso.sha256) ||
            | Ashburn | [LATEST](https://www2.as.steamfork.org/images/installer/steamfork-rel-latest-x86_64.iso) | [SHA256](https://www2.as.steamfork.org/images/installer/steamfork-rel-latest-x86_64.iso.sha256) ||
            For installation instructions and other documentation, visit the [3.6 project page](https://github.com/SteamFork).

          prerelease: false
          artifacts: release/images/rel/images/package-versions.txt
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: SteamFork
          repo: distribution
