# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2025 SteamFork (https://github.com/SteamFork)
# This workflow builds and releases testing images for the SteamFork distribution.

name: Testing - Image Build and Release
permissions:
  contents: write
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 1440
    runs-on: 3.7
    steps:
      - name: Set up Git
        env:
          BRANCH_NAME: 3.7
        run: |
          if [ ! -d ".git" ]; then
            git init
            git remote add origin https://github.com/${{ github.repository }}.git
          fi
          git fetch origin "${BRANCH_NAME}"
          if [ "$(git branch --list "${BRANCH_NAME}")" ]; then
            git checkout "${BRANCH_NAME}"
          else
            git checkout -b "${BRANCH_NAME}" origin/"${BRANCH_NAME}"
          fi

      - name: Set the tag
        id: tag
        run: echo "tag=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Set the version
        id: version
        run: echo "version=$(date +'%Y%m%d.%H%M')" >> $GITHUB_OUTPUT
      - name: Build Testing Image
        run: |
          set -e
          make image testing BUILD_VER="${{ steps.version.outputs.version }}"
  sync:
    if: github.repository == 'SteamFork/distribution' && github.ref == 'refs/heads/3.7'
    timeout-minutes: 1440
    runs-on: 3.7
    needs: build
    steps:
      - name: Sync testing images to the primary instance
        run: |
          set -e
          make images-sync
      - name: Sync images to each mirror
        run: |
          set -e
          make mirrors-sync