#!/bin/sh

# AMD PStates are not always active on boot until they're switched.
for STATE in passive active
do
  if [ -e "/sys/devices/system/cpu/amd_pstate/status" ]
  then
    echo ${STATE} >/sys/devices/system/cpu/amd_pstate/status
  fi
done

