#!/bin/sh

# Set power saving mode on fingerprint readers and then disable them since we can't use them.

READER=$(grep -iE '(Fing|ETU905A86-E)' /sys/bus/usb/devices/*/product 2>/dev/null | awk 'BEGIN {FS="/"} {printf $6}')
if [ -n "${READER}" ]
then
  echo auto > /sys/bus/usb/devices/${READER}/power/control 2>/dev/null
  echo ${READER} >/sys/bus/usb/drivers/usb/unbind
fi
